spring:
  application:
    name: groupy-application

  datasource:
    url: jdbc:mysql://localhost:3306/instagram_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

app:
 frontend-url: http://localhost:3000

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}

cloudinary:
  cloud-name: dax0rgeys
  api-key: 522414747294619
  api-secret: kLtScFr_ruJELXFkrR34CTd2CTU

# JWT Configuration
jwt:
  secret: my-super-secure-very-long-512-bit-secret-key-for-groupy-project-2026
  # expiration: 86400000 # 1 day
  # refresh-expiration: 604800000 # 7 days

logging:
  level:
    com.groupy: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8080
