spring:
  application:
    name: instagram-application

  datasource:
    url: jdbc:mysql://localhost:3306/instagram_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# JWT Configuration
jwt:
  secret: my-super-secure-very-long-512-bit-secret-key-for-instagram-project-2026
  # expiration: 86400000 # 1 day
  # refresh-expiration: 604800000 # 7 days

logging:
  level:
    com.instagram: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 8081
