spring:
  application:
    name: groupy-application

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
     maximum-pool-size: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

cloudinary:
  cloud-name: dax0rgeys
  api-key: 522414747294619
  api-secret: kLtScFr_ruJELXFkrR34CTd2CTU

# JWT Configuration
jwt:
  secret: my-super-secure-very-long-512-bit-secret-key-for-groupy-project-2026
  # expiration: 86400000 # 1 day
  # refresh-expiration: 604800000 # 7 days

logging:
  level:
    com.groupy: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: ${PORT:8080}
